"""rename department

Revision ID: ff947cf5756b
Revises: 4a6bc70efa36
Create Date: 2024-06-29 00:19:27.696356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff947cf5756b'
down_revision = '4a6bc70efa36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
